title: "html-midi-player"
tagline: "Play and display MIDI files online"
description: "A web component for MIDI playback and visualization in the browser. It allows playing MIDI files online."

github:
  is_project_page: true
  repository_name: html-midi-player
  repository_url: https://github.com/cifkao/html-midi-player
  owner_name: Ondřej Cífka
  owner_url: https://github.com/cifkao
  project_tagline: Play and display MIDI files on the web

theme: jekyll-theme-cayman

markdown: kramdown

plugins:
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      layout: default

baseurl: /html-midi-player/

exclude:
  - README.md
  - assets/js
  - node_modules
  - vendor
  - Gemfile.lock
  - package.json
  - yarn.lock
  - yarn-error.log

keep_files:
  - assets/js
